#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '-----pre-push hook started-----'

# Run __tests__
if ! npm run test; then
    echo 'Tests failed'
    exit 1
fi

echo '-----__tests__ completed-----'
exit 0
