#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '-----pre-push hook started-----'

# Run tests
if ! npm run test; then
    echo 'Tests failed'
    exit 1
fi

echo '-----tests completed-----'
exit 0
